// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitle("LetygaLabs.Graph.Export")>]
[<assembly: AssemblyProduct("LetygaLabs.Graph.Export")>]
[<assembly: AssemblyVersion("0.1.0")>]
[<assembly: AssemblyMetadata("ReleaseDate", "2017-03-17T00:00:00.0000000")>]
[<assembly: AssemblyFileVersion("0.1.0")>]
[<assembly: AssemblyInformationalVersion("0.1.0")>]
[<assembly: AssemblyMetadata("ReleaseChannel", "release")>]
[<assembly: AssemblyMetadata("GitHash", "bb8964b54bee133e9af64d316dc2cfee16df7f72")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "LetygaLabs.Graph.Export"

    [<Literal>]
    let AssemblyProduct = "LetygaLabs.Graph.Export"

    [<Literal>]
    let AssemblyVersion = "0.1.0"

    [<Literal>]
    let AssemblyMetadata_ReleaseDate = "2017-03-17T00:00:00.0000000"

    [<Literal>]
    let AssemblyFileVersion = "0.1.0"

    [<Literal>]
    let AssemblyInformationalVersion = "0.1.0"

    [<Literal>]
    let AssemblyMetadata_ReleaseChannel = "release"

    [<Literal>]
    let AssemblyMetadata_GitHash = "bb8964b54bee133e9af64d316dc2cfee16df7f72"
